service: ayoub-dynamic-image-resizing-function

plugins:
  - serverless-plugin-tracing
  - serverless-plugin-datadog

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE, 'dev'}
  profile: serverless-ayoub
  tracing:
    lambda: true
    apiGateway: true
  region: ${env:REGION, 'eu-west-3'}
  apiGateway:
    binaryMediaTypes:
    - '*/*'
  logs:
    restApi:
      level: ERROR
  environment:
    S3_BUCKET: ${env:S3_BUCKET}
    REGION: ${env:REGION}
    AUTH_USERNAME: ${env:AUTH_USERNAME}
    AUTH_PASSWORD: ${env:AUTH_PASSWORD}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${env:S3_BUCKET}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::${env:S3_BUCKET}"
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  image:
    handler: app.lambdaHandler
    events:
      - http:
          path: image
          method: post
          authorizer:
            name: basicAuth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request
  basicAuth:
    handler: auth.handler

custom:
  datadog:
    addLayers: true
    apiKey: ${env:DD_API_KEY}
    flushMetricsToLogs: false

resources:
  Resources:
    GatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: '401'